Repository realm/realm-java, pull requests merged in 2018-11, with the labels that each got.

#6224 Ignore same values when using copyToRealm
  CHANGELOG.md
  examples/unitTestExample/build.gradle
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmBenchmarks.java
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmOrUpdateBenchmarks.java
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmQueryBenchmarks.java
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/entities/AllTypesPrimaryKey.java
  realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
  realm/realm-annotations-processor/src/main/java/io/realm/processor/OsObjectBuilderTypeHelper.java
  realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
  realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java
  realm/realm-annotations-processor/src/main/java/io/realm/processor/TypeMirrors.java
  realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.java
  realm/realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java
  realm/realm-annotations-processor/src/test/resources/io/realm/some_test_AllTypesRealmProxy.java
  realm/realm-annotations-processor/src/test/resources/io/realm/some_test_BooleansRealmProxy.java
  realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NamePolicyMixedClassSettingsRealmProxy.java
  realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NamePolicyModuleDefaultsRealmProxy.java
  realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NullTypesRealmProxy.java
  realm/realm-annotations-processor/src/test/resources/io/realm/some_test_SimpleRealmProxy.java
  realm/realm-library/src/androidTest/java/io/realm/MutableRealmIntegerTests.java
  realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
  realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
  realm/realm-library/src/main/cpp/CMakeLists.txt
  realm/realm-library/src/main/cpp/io_realm_internal_OsObjectSchemaInfo.cpp
  realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsObjectBuilder.cpp
  realm/realm-library/src/main/cpp/java_object_accessor.hpp
  realm/realm-library/src/main/cpp/util.cpp
  realm/realm-library/src/main/cpp/util.hpp
  realm/realm-library/src/main/java/io/realm/BaseRealm.java
  realm/realm-library/src/main/java/io/realm/ImportFlag.java
  realm/realm-library/src/main/java/io/realm/Realm.java
  realm/realm-library/src/main/java/io/realm/RealmList.java
  realm/realm-library/src/main/java/io/realm/RealmObject.java
  realm/realm-library/src/main/java/io/realm/internal/OsObjectSchemaInfo.java
  realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java
  realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java
  realm/realm-library/src/main/java/io/realm/internal/Table.java
  realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java
  realm/realm-library/src/main/java/io/realm/internal/Util.java
  realm/realm-library/src/main/java/io/realm/internal/modules/CompositeMediator.java
  realm/realm-library/src/main/java/io/realm/internal/modules/FilterableMediator.java
  realm/realm-library/src/main/java/io/realm/internal/objectstore/OsObjectBuilder.java
  realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java
  realm/realm-library/src/testUtils/java/io/realm/entities/PrimaryKeyAsLong.java
Labels: T:Feature

#6270 Add support for setting a custom User-Agent
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/MyApplication.java
  library-build-transformer/src/main/kotlin/io/realm/buildtransformer/asm/visitors/AnnotatedCodeStripVisitor.kt
  library-build-transformer/src/main/kotlin/io/realm/buildtransformer/asm/visitors/AnnotationVisitor.kt
  library-build-transformer/src/test/java/io/realm/buildtransformer/testclasses/SimpleTestMethods.java
  library-build-transformer/src/test/kotlin/io/realm/buildtransformer/VisitorTests.kt
  realm/realm-library/src/main/cpp/io_realm_SyncManager.cpp
  realm/realm-library/src/main/java/io/realm/BaseRealm.java
  realm/realm-library/src/main/java/io/realm/Realm.java
  realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java
  realm/realm-library/src/objectServer/java/io/realm/ObjectServer.java
  realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
  realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
Labels: T:Enhancement

#6073 Add support for uploading and downloading changes with a timeout
  CHANGELOG.md
  realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
  realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
  realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
  realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
  realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java
Labels: T:Feature

#5133 Add support for bulk updating fields in query results
  CHANGELOG.md
  examples/moduleExample/app/build.gradle
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmBenchmarks.java
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmOrUpdateBenchmarks.java
  realm/kotlin-extensions/build.gradle
  realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
  realm/realm-library/src/androidTest/java/io/realm/entities/MappedAllJavaTypes.java
  realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp
  realm/realm-library/src/main/java/io/realm/RealmResults.java
  realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java
  realm/realm-library/src/main/java/io/realm/internal/NativeContext.java
  realm/realm-library/src/main/java/io/realm/internal/OsResults.java
  realm/realm-library/src/main/java/io/realm/internal/objectstore/OsObjectBuilder.java
Labels: T:Enhancement

#6285 Fix Gradle cache not working in parallel builds
  Jenkinsfile
Labels: T:Internal
