Repository realm/realm-java, pull requests merged in 2019-11, with the labels that each got.

#6651 Upgrade benchmarks to use latest release
  library-benchmarks/build.gradle
  library-benchmarks/gradle/wrapper/gradle-wrapper.properties
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmBenchmarks.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmOrUpdateBenchmarks.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmAllocBenchmarks.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmBenchmarks.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmInsertBenchmark.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmObjectReadBenchmarks.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmObjectWriteBenchmarks.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmQueryBenchmarks.kt
  library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmResultsBenchmarks.kt
Labels: T-Enhancement

#6647 Upgrade sync + fix encryption race
  CHANGELOG.md
  dependencies.list
  realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
  realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
  realm/realm-library/src/testUtils/java/io/realm/entities/AllTypes.java
Labels: T-Bug-Crash

#6662 Updated README
  README.md
Labels: T-Doc

#6663 Fix Proguard setup for release builds using R8
  CHANGELOG.md
  realm/realm-library/proguard-rules-consumer-common.pro
Labels: T-Bug-Crash

#6664 Update to latest sync release
  CHANGELOG.md
  dependencies.list
Labels: T-Enhancement

#6652 Realm plugin: consider kotlin-multiplatform plugin
  gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy
Labels: Pipeline-Review
