Repository realm/realm-java, pull requests merged in 2019-08, with the labels that each got.

#6573 Add instructions for building Realm from a local source
  README.md
  realm/realm-library/build.gradle
  realm/realm-library/src/main/cpp/CMake/RealmCore.cmake
  realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
Labels: T:Enhancement

#6575 Correctly copy JAR files in the Realm transformer
  CHANGELOG.md
  realm-transformer/build.gradle
  realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt
  realm-transformer/src/main/kotlin/io/realm/transformer/build/BuildTemplate.kt
  realm-transformer/src/main/kotlin/io/realm/transformer/build/FullBuild.kt
  realm-transformer/src/main/kotlin/io/realm/transformer/build/IncrementalBuild.kt
Labels: T:Bug-Crash

#6579 ROS-49 Deprecate nickname provider
  CHANGELOG.md
  realm/realm-library/src/objectServer/java/io/realm/SyncCredentials.java
Labels: T:Enhancement

#6582 Fix crash if combining @RealmField and @LinkingObjects
  CHANGELOG.md
  realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt
  realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsManagedTests.java
  realm/realm-library/src/testUtils/java/io/realm/entities/BacklinkWithOverridenNames.java
Labels: T:Bug-Crash

#6599 [RJAVA-4] Bypass the sync proxy on Cloud
  CHANGELOG.md
  realm/realm-library/src/main/cpp/io_realm_SyncSession.cpp
  realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
  realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthenticateResponse.java
  realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/SyncWorker.java
Labels: T-Enhancement
