Repository realm/realm-java, pull requests merged in 2019-02, with the labels that each got.

#6413 Convert ObjectServerExample to Kotlin and use data binding
  Dockerfile
  examples/objectServerExample/README.md
  examples/objectServerExample/build.gradle
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/CounterActivity.java
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/CounterActivity.kt
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/LoginActivity.java
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/LoginActivity.kt
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/MyApplication.kt
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/model/CRDTCounter.java
  examples/objectServerExample/src/main/java/io/realm/examples/objectserver/model/CRDTCounter.kt
  examples/objectServerExample/src/main/res/layout/activity_counter.xml
  examples/objectServerExample/src/main/res/layout/activity_login.xml
  examples/objectServerExample/src/main/res/values/strings.xml
  realm/build.gradle
Labels: T:Enhancement

#6402 Fix merge from 11d073 to next-major
  CHANGELOG.md
Labels: T:Internal

#6437 Fixed JNI reference not released correctly
  CHANGELOG.md
  realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
Labels: T:Bug-Crash

#6446 Fix ROS not being able to start
  dependencies.list
  tools/sync_test_server/ros/tsconfig.json
Labels: T:Internal
